package com.juniormelgarejo.cats.domain

val rawInput = """
    {
    "data": [
        {
            "id": "jWmLOfa",
            "title": "Cat and owl best friends",
            "description": null,
            "datetime": 1573838752,
            "cover": "FkIxe3R",
            "cover_width": 960,
            "cover_height": 720,
            "account_url": "nidtyaso",
            "account_id": 116221495,
            "privacy": "hidden",
            "layout": "blog",
            "views": 28,
            "link": "https://imgur.com/a/jWmLOfa",
            "ups": 5,
            "downs": 1,
            "points": 4,
            "score": 4,
            "is_album": true,
            "vote": null,
            "favorite": false,
            "nsfw": false,
            "section": "",
            "comment_count": 4,
            "favorite_count": 0,
            "topic": "No Topic",
            "topic_id": 29,
            "images_count": 1,
            "in_gallery": true,
            "is_ad": false,
            "tags": [
                {
                    "name": "funny",
                    "display_name": "funny",
                    "followers": 3344126,
                    "total_items": 350335,
                    "following": false,
                    "is_whitelisted": false,
                    "background_hash": "9r1qCDq",
                    "thumbnail_hash": null,
                    "accent": "633875",
                    "background_is_animated": false,
                    "thumbnail_is_animated": false,
                    "is_promoted": false,
                    "description": "LOLs, ROFLs, LMAOs",
                    "logo_hash": null,
                    "logo_destination_url": null,
                    "description_annotations": {}
                },
                {
                    "name": "cat",
                    "display_name": "cat",
                    "followers": 958165,
                    "total_items": 53025,
                    "following": false,
                    "is_whitelisted": false,
                    "background_hash": "xeEIpAn",
                    "thumbnail_hash": null,
                    "accent": "159559",
                    "background_is_animated": false,
                    "thumbnail_is_animated": false,
                    "is_promoted": false,
                    "description": "feline friends",
                    "logo_hash": null,
                    "logo_destination_url": null,
                    "description_annotations": {}
                },
                {
                    "name": "cats",
                    "display_name": "cats",
                    "followers": 181278,
                    "total_items": 12515,
                    "following": false,
                    "is_whitelisted": false,
                    "background_hash": "xeEIpAn",
                    "thumbnail_hash": null,
                    "accent": "BF63A7",
                    "background_is_animated": false,
                    "thumbnail_is_animated": false,
                    "is_promoted": false,
                    "description": "Our feline friends",
                    "logo_hash": null,
                    "logo_destination_url": null,
                    "description_annotations": {}
                },
                {
                    "name": "aww",
                    "display_name": "aww",
                    "followers": 1812345,
                    "total_items": 90384,
                    "following": false,
                    "is_whitelisted": false,
                    "background_hash": "avRBRpN",
                    "thumbnail_hash": null,
                    "accent": "60AEBB",
                    "background_is_animated": false,
                    "thumbnail_is_animated": false,
                    "is_promoted": false,
                    "description": "cute and adorable",
                    "logo_hash": null,
                    "logo_destination_url": null,
                    "description_annotations": {}
                },
                {
                    "name": "owl",
                    "display_name": "owl",
                    "followers": 15963,
                    "total_items": 1209,
                    "following": false,
                    "is_whitelisted": false,
                    "background_hash": "Ikykl3U",
                    "thumbnail_hash": null,
                    "accent": "008261",
                    "background_is_animated": false,
                    "thumbnail_is_animated": false,
                    "is_promoted": false,
                    "description": "",
                    "logo_hash": null,
                    "logo_destination_url": null,
                    "description_annotations": {}
                }
            ],
            "ad_type": 0,
            "ad_url": "",
            "in_most_viral": false,
            "include_album_ads": false,
            "images": [
                {
                    "id": "FkIxe3R",
                    "title": null,
                    "description": null,
                    "datetime": 1573838692,
                    "type": "video/mp4",
                    "animated": true,
                    "width": 960,
                    "height": 720,
                    "size": 2857917,
                    "views": 119,
                    "bandwidth": 340092123,
                    "vote": null,
                    "favorite": false,
                    "nsfw": null,
                    "section": null,
                    "account_url": null,
                    "account_id": null,
                    "is_ad": false,
                    "in_most_viral": false,
                    "has_sound": false,
                    "tags": [],
                    "ad_type": 0,
                    "ad_url": "",
                    "edited": "0",
                    "in_gallery": false,
                    "link": "https://i.imgur.com/FkIxe3R.mp4",
                    "mp4_size": 2857917,
                    "mp4": "https://i.imgur.com/FkIxe3R.mp4",
                    "gifv": "https://i.imgur.com/FkIxe3R.gifv",
                    "hls": "https://i.imgur.com/FkIxe3R.m3u8",
                    "processing": {
                        "status": "completed"
                    },
                    "comment_count": null,
                    "favorite_count": null,
                    "ups": null,
                    "downs": null,
                    "points": null,
                    "score": null
                }
            ],
            "ad_config": {
                "safeFlags": [
                    "album",
                    "in_gallery",
                    "onsfw_mod_safe",
                    "gallery",
                    "page_load"
                ],
                "highRiskFlags": [],
                "unsafeFlags": [
                    "sixth_mod_unsafe",
                    "under_10",
                    "updated_date"
                ],
                "wallUnsafeFlags": [],
                "showsAds": false
            }
        },
        {
            "id": "hfhEqHS",
            "title": "I think he likes it or something",
            "description": null,
            "datetime": 1573838571,
            "cover": "YdALdO5",
            "cover_width": 720,
            "cover_height": 1280,
            "account_url": "chcalder93",
            "account_id": 103696909,
            "privacy": "hidden",
            "layout": "blog",
            "views": 12,
            "link": "https://imgur.com/a/hfhEqHS",
            "ups": 4,
            "downs": 0,
            "points": 4,
            "score": 4,
            "is_album": true,
            "vote": null,
            "favorite": false,
            "nsfw": false,
            "section": "",
            "comment_count": 1,
            "favorite_count": 0,
            "topic": "No Topic",
            "topic_id": 29,
            "images_count": 1,
            "in_gallery": true,
            "is_ad": false,
            "tags": [
                {
                    "name": "cute",
                    "display_name": "cute",
                    "followers": 113342,
                    "total_items": 174555,
                    "following": false,
                    "is_whitelisted": false,
                    "background_hash": "MifWJps",
                    "thumbnail_hash": null,
                    "accent": "3BA3B1",
                    "background_is_animated": false,
                    "thumbnail_is_animated": false,
                    "is_promoted": false,
                    "description": "",
                    "logo_hash": null,
                    "logo_destination_url": null,
                    "description_annotations": {}
                },
                {
                    "name": "cats",
                    "display_name": "cats",
                    "followers": 181278,
                    "total_items": 12515,
                    "following": false,
                    "is_whitelisted": false,
                    "background_hash": "xeEIpAn",
                    "thumbnail_hash": null,
                    "accent": "BF63A7",
                    "background_is_animated": false,
                    "thumbnail_is_animated": false,
                    "is_promoted": false,
                    "description": "Our feline friends",
                    "logo_hash": null,
                    "logo_destination_url": null,
                    "description_annotations": {}
                },
                {
                    "name": "baby",
                    "display_name": "baby",
                    "followers": 3523,
                    "total_items": 3249,
                    "following": false,
                    "is_whitelisted": false,
                    "background_hash": "gmFssAG",
                    "thumbnail_hash": null,
                    "accent": "51535A",
                    "background_is_animated": false,
                    "thumbnail_is_animated": false,
                    "is_promoted": false,
                    "description": "",
                    "logo_hash": null,
                    "logo_destination_url": null,
                    "description_annotations": {}
                },
                {
                    "name": "swing",
                    "display_name": "swing",
                    "followers": 80,
                    "total_items": 41,
                    "following": false,
                    "is_whitelisted": false,
                    "background_hash": "eWY7qg5",
                    "thumbnail_hash": null,
                    "accent": "2E6197",
                    "background_is_animated": false,
                    "thumbnail_is_animated": false,
                    "is_promoted": false,
                    "description": "",
                    "logo_hash": null,
                    "logo_destination_url": null,
                    "description_annotations": {}
                },
                {
                    "name": "wholesome",
                    "display_name": "wholesome",
                    "followers": 33068,
                    "total_items": 2,
                    "following": false,
                    "is_whitelisted": false,
                    "background_hash": "W5yeBvr",
                    "thumbnail_hash": null,
                    "accent": "5D85C3",
                    "background_is_animated": false,
                    "thumbnail_is_animated": false,
                    "is_promoted": false,
                    "description": "",
                    "logo_hash": null,
                    "logo_destination_url": null,
                    "description_annotations": {}
                }
            ],
            "ad_type": 0,
            "ad_url": "",
            "in_most_viral": false,
            "include_album_ads": false,
            "images": [
                {
                    "id": "YdALdO5",
                    "title": null,
                    "description": null,
                    "datetime": 1573837442,
                    "type": "video/mp4",
                    "animated": true,
                    "width": 720,
                    "height": 1280,
                    "size": 8359729,
                    "views": 139,
                    "bandwidth": 1162002331,
                    "vote": null,
                    "favorite": false,
                    "nsfw": null,
                    "section": null,
                    "account_url": null,
                    "account_id": null,
                    "is_ad": false,
                    "in_most_viral": false,
                    "has_sound": true,
                    "tags": [],
                    "ad_type": 0,
                    "ad_url": "",
                    "edited": "0",
                    "in_gallery": false,
                    "link": "https://i.imgur.com/YdALdO5.mp4",
                    "mp4_size": 8359729,
                    "mp4": "https://i.imgur.com/YdALdO5.mp4",
                    "gifv": "https://i.imgur.com/YdALdO5.gifv",
                    "hls": "https://i.imgur.com/YdALdO5.m3u8",
                    "processing": {
                        "status": "completed"
                    },
                    "comment_count": null,
                    "favorite_count": null,
                    "ups": null,
                    "downs": null,
                    "points": null,
                    "score": null
                }
            ],
            "ad_config": {
                "safeFlags": [
                    "in_gallery"
                ],
                "highRiskFlags": [],
                "unsafeFlags": [
                    "sixth_mod_unsafe"
                ],
                "wallUnsafeFlags": [],
                "showsAds": false
            }
        },
        {
            "id": "Q2Gwq3N",
            "title": "Leopard 2 A5",
            "description": null,
            "datetime": 1573838140,
            "cover": "dUZTfoE",
            "cover_width": 1225,
            "cover_height": 796,
            "account_url": "barenton",
            "account_id": 39135512,
            "privacy": "hidden",
            "layout": "blog",
            "views": 37,
            "link": "https://imgur.com/a/Q2Gwq3N",
            "ups": 2,
            "downs": 0,
            "points": 2,
            "score": 2,
            "is_album": true,
            "vote": null,
            "favorite": false,
            "nsfw": false,
            "section": "",
            "comment_count": 0,
            "favorite_count": 0,
            "topic": "No Topic",
            "topic_id": 29,
            "images_count": 1,
            "in_gallery": true,
            "is_ad": false,
            "tags": [
                {
                    "name": "cats",
                    "display_name": "cats",
                    "followers": 181278,
                    "total_items": 12515,
                    "following": false,
                    "is_whitelisted": false,
                    "background_hash": "xeEIpAn",
                    "thumbnail_hash": null,
                    "accent": "BF63A7",
                    "background_is_animated": false,
                    "thumbnail_is_animated": false,
                    "is_promoted": false,
                    "description": "Our feline friends",
                    "logo_hash": null,
                    "logo_destination_url": null,
                    "description_annotations": {}
                },
                {
                    "name": "military",
                    "display_name": "military",
                    "followers": 14202,
                    "total_items": 2289,
                    "following": false,
                    "is_whitelisted": false,
                    "background_hash": "oAtvuB2",
                    "thumbnail_hash": null,
                    "accent": null,
                    "background_is_animated": false,
                    "thumbnail_is_animated": false,
                    "is_promoted": false,
                    "description": "",
                    "logo_hash": null,
                    "logo_destination_url": null,
                    "description_annotations": {}
                },
                {
                    "name": "aww",
                    "display_name": "aww",
                    "followers": 1812324,
                    "total_items": 90382,
                    "following": false,
                    "is_whitelisted": false,
                    "background_hash": "avRBRpN",
                    "thumbnail_hash": null,
                    "accent": "60AEBB",
                    "background_is_animated": false,
                    "thumbnail_is_animated": false,
                    "is_promoted": false,
                    "description": "cute and adorable",
                    "logo_hash": null,
                    "logo_destination_url": null,
                    "description_annotations": {}
                },
                {
                    "name": "the_more_you_know",
                    "display_name": "the more you know",
                    "followers": 951980,
                    "total_items": 3948,
                    "following": false,
                    "is_whitelisted": false,
                    "background_hash": "cHaxWH1",
                    "thumbnail_hash": null,
                    "accent": "21B86E",
                    "background_is_animated": false,
                    "thumbnail_is_animated": false,
                    "is_promoted": false,
                    "description": "facts and knowledge",
                    "logo_hash": null,
                    "logo_destination_url": null,
                    "description_annotations": {}
                }
            ],
            "ad_type": 0,
            "ad_url": "",
            "in_most_viral": false,
            "include_album_ads": false,
            "images": [
                {
                    "id": "dUZTfoE",
                    "title": null,
                    "description": "Giant Military Cats\n@giantcat9",
                    "datetime": 1573838081,
                    "type": "image/jpeg",
                    "animated": false,
                    "width": 1225,
                    "height": 796,
                    "size": 309672,
                    "views": 90,
                    "bandwidth": 27870480,
                    "vote": null,
                    "favorite": false,
                    "nsfw": null,
                    "section": null,
                    "account_url": null,
                    "account_id": null,
                    "is_ad": false,
                    "in_most_viral": false,
                    "has_sound": false,
                    "tags": [],
                    "ad_type": 0,
                    "ad_url": "",
                    "edited": "0",
                    "in_gallery": false,
                    "link": "https://i.imgur.com/dUZTfoE.jpg",
                    "comment_count": null,
                    "favorite_count": null,
                    "ups": null,
                    "downs": null,
                    "points": null,
                    "score": null
                }
            ],
            "ad_config": {
                "safeFlags": [
                    "album",
                    "in_gallery",
                    "onsfw_mod_safe",
                    "gallery"
                ],
                "highRiskFlags": [],
                "unsafeFlags": [
                    "sixth_mod_unsafe",
                    "under_10"
                ],
                "wallUnsafeFlags": [],
                "showsAds": false
            }
        },
        {
            "id": "A3XmPah",
            "title": "My cat passed away today after 18 year and 9 months. I'll miss you Bola 8",
            "description": null,
            "datetime": 1573837667,
            "cover": "Ltxvf11",
            "cover_width": 1812,
            "cover_height": 1173,
            "account_url": "Anarch157a",
            "account_id": 48218784,
            "privacy": "hidden",
            "layout": "blog",
            "views": 62,
            "link": "https://imgur.com/a/A3XmPah",
            "ups": 4,
            "downs": 0,
            "points": 4,
            "score": 4,
            "is_album": true,
            "vote": null,
            "favorite": false,
            "nsfw": false,
            "section": "",
            "comment_count": 1,
            "favorite_count": 0,
            "topic": "No Topic",
            "topic_id": 29,
            "images_count": 3,
            "in_gallery": true,
            "is_ad": false,
            "tags": [
                {
                    "name": "cat",
                    "display_name": "cat",
                    "followers": 958166,
                    "total_items": 53025,
                    "following": false,
                    "is_whitelisted": false,
                    "background_hash": "xeEIpAn",
                    "thumbnail_hash": null,
                    "accent": "159559",
                    "background_is_animated": false,
                    "thumbnail_is_animated": false,
                    "is_promoted": false,
                    "description": "feline friends",
                    "logo_hash": null,
                    "logo_destination_url": null,
                    "description_annotations": {}
                },
                {
                    "name": "cats",
                    "display_name": "cats",
                    "followers": 181278,
                    "total_items": 12515,
                    "following": false,
                    "is_whitelisted": false,
                    "background_hash": "xeEIpAn",
                    "thumbnail_hash": null,
                    "accent": "BF63A7",
                    "background_is_animated": false,
                    "thumbnail_is_animated": false,
                    "is_promoted": false,
                    "description": "Our feline friends",
                    "logo_hash": null,
                    "logo_destination_url": null,
                    "description_annotations": {}
                },
                {
                    "name": "friends",
                    "display_name": "friends",
                    "followers": 2475,
                    "total_items": 2161,
                    "following": false,
                    "is_whitelisted": false,
                    "background_hash": "1RFUuDD",
                    "thumbnail_hash": null,
                    "accent": null,
                    "background_is_animated": false,
                    "thumbnail_is_animated": false,
                    "is_promoted": false,
                    "description": "",
                    "logo_hash": null,
                    "logo_destination_url": null,
                    "description_annotations": {}
                },
                {
                    "name": "you_will_be_missed",
                    "display_name": "you will be missed",
                    "followers": 14,
                    "total_items": 1,
                    "following": false,
                    "is_whitelisted": false,
                    "background_hash": "gmFssAG",
                    "thumbnail_hash": null,
                    "accent": "51535A",
                    "background_is_animated": false,
                    "thumbnail_is_animated": false,
                    "is_promoted": false,
                    "description": "",
                    "logo_hash": null,
                    "logo_destination_url": null,
                    "description_annotations": {}
                }
            ],
            "ad_type": 0,
            "ad_url": "",
            "in_most_viral": false,
            "include_album_ads": false,
            "images": [
                {
                    "id": "5o4ZSgP",
                    "title": null,
                    "description": "But she did like some enterprise networking gear...",
                    "datetime": 1573837378,
                    "type": "image/jpeg",
                    "animated": false,
                    "width": 5248,
                    "height": 3936,
                    "size": 2420804,
                    "views": 168,
                    "bandwidth": 406695072,
                    "vote": null,
                    "favorite": false,
                    "nsfw": null,
                    "section": null,
                    "account_url": null,
                    "account_id": null,
                    "is_ad": false,
                    "in_most_viral": false,
                    "has_sound": false,
                    "tags": [],
                    "ad_type": 0,
                    "ad_url": "",
                    "edited": "0",
                    "in_gallery": false,
                    "link": "https://i.imgur.com/5o4ZSgP.jpg",
                    "comment_count": null,
                    "favorite_count": null,
                    "ups": null,
                    "downs": null,
                    "points": null,
                    "score": null
                },
                {
                    "id": "Ltxvf11",
                    "title": null,
                    "description": "She was sooo tiny...",
                    "datetime": 1573837336,
                    "type": "image/jpeg",
                    "animated": false,
                    "width": 1812,
                    "height": 1173,
                    "size": 78391,
                    "views": 169,
                    "bandwidth": 13248079,
                    "vote": null,
                    "favorite": false,
                    "nsfw": null,
                    "section": null,
                    "account_url": null,
                    "account_id": null,
                    "is_ad": false,
                    "in_most_viral": false,
                    "has_sound": false,
                    "tags": [],
                    "ad_type": 0,
                    "ad_url": "",
                    "edited": "0",
                    "in_gallery": false,
                    "link": "https://i.imgur.com/Ltxvf11.jpg",
                    "comment_count": null,
                    "favorite_count": null,
                    "ups": null,
                    "downs": null,
                    "points": null,
                    "score": null
                },
                {
                    "id": "2EkziLE",
                    "title": null,
                    "description": "She's scared of that big, mean Unix server in back...",
                    "datetime": 1573837360,
                    "type": "image/jpeg",
                    "animated": false,
                    "width": 640,
                    "height": 480,
                    "size": 98480,
                    "views": 121,
                    "bandwidth": 11916080,
                    "vote": null,
                    "favorite": false,
                    "nsfw": null,
                    "section": null,
                    "account_url": null,
                    "account_id": null,
                    "is_ad": false,
                    "in_most_viral": false,
                    "has_sound": false,
                    "tags": [],
                    "ad_type": 0,
                    "ad_url": "",
                    "edited": "0",
                    "in_gallery": false,
                    "link": "https://i.imgur.com/2EkziLE.jpg",
                    "comment_count": null,
                    "favorite_count": null,
                    "ups": null,
                    "downs": null,
                    "points": null,
                    "score": null
                }
            ],
            "ad_config": {
                "safeFlags": [
                    "album",
                    "in_gallery",
                    "onsfw_mod_safe",
                    "gallery"
                ],
                "highRiskFlags": [],
                "unsafeFlags": [
                    "sixth_mod_unsafe",
                    "under_10"
                ],
                "wallUnsafeFlags": [],
                "showsAds": false
            }
        },
        {
            "id": "1ojTQbS",
            "title": "Today's Cat",
            "description": null,
            "datetime": 1573837082,
            "cover": "mTDt6PG",
            "cover_width": 1024,
            "cover_height": 680,
            "account_url": "Lyssahumana",
            "account_id": 98442989,
            "privacy": "hidden",
            "layout": "blog",
            "views": 70,
            "link": "https://imgur.com/a/1ojTQbS",
            "ups": 4,
            "downs": 0,
            "points": 4,
            "score": 4,
            "is_album": true,
            "vote": null,
            "favorite": false,
            "nsfw": false,
            "section": "",
            "comment_count": 0,
            "favorite_count": 0,
            "topic": "No Topic",
            "topic_id": 29,
            "images_count": 1,
            "in_gallery": true,
            "is_ad": false,
            "tags": [
                {
                    "name": "cats",
                    "display_name": "cats",
                    "followers": 181278,
                    "total_items": 12515,
                    "following": false,
                    "is_whitelisted": false,
                    "background_hash": "xeEIpAn",
                    "thumbnail_hash": null,
                    "accent": "BF63A7",
                    "background_is_animated": false,
                    "thumbnail_is_animated": false,
                    "is_promoted": false,
                    "description": "Our feline friends",
                    "logo_hash": null,
                    "logo_destination_url": null,
                    "description_annotations": {}
                },
                {
                    "name": "todayscats",
                    "display_name": "todayscats",
                    "followers": 104,
                    "total_items": 0,
                    "following": false,
                    "is_whitelisted": false,
                    "background_hash": "GEpMqov",
                    "thumbnail_hash": null,
                    "accent": "1E5F43",
                    "background_is_animated": false,
                    "thumbnail_is_animated": false,
                    "is_promoted": false,
                    "description": "",
                    "logo_hash": null,
                    "logo_destination_url": null,
                    "description_annotations": {}
                }
            ],
            "ad_type": 0,
            "ad_url": "",
            "in_most_viral": false,
            "include_album_ads": false,
            "images": [
                {
                    "id": "mTDt6PG",
                    "title": null,
                    "description": "#cats #todayscats",
                    "datetime": 1573837070,
                    "type": "image/jpeg",
                    "animated": false,
                    "width": 1024,
                    "height": 680,
                    "size": 411658,
                    "views": 112,
                    "bandwidth": 46105696,
                    "vote": null,
                    "favorite": false,
                    "nsfw": null,
                    "section": null,
                    "account_url": null,
                    "account_id": null,
                    "is_ad": false,
                    "in_most_viral": false,
                    "has_sound": false,
                    "tags": [],
                    "ad_type": 0,
                    "ad_url": "",
                    "edited": "0",
                    "in_gallery": false,
                    "link": "https://i.imgur.com/mTDt6PG.jpg",
                    "comment_count": null,
                    "favorite_count": null,
                    "ups": null,
                    "downs": null,
                    "points": null,
                    "score": null
                }
            ],
            "ad_config": {
                "safeFlags": [
                    "album",
                    "in_gallery",
                    "onsfw_mod_safe",
                    "gallery"
                ],
                "highRiskFlags": [],
                "unsafeFlags": [
                    "sixth_mod_unsafe",
                    "under_10"
                ],
                "wallUnsafeFlags": [],
                "showsAds": false
            }
        },
        {
            "id": "YkoYJnm",
            "title": "What a fluffy ❤️",
            "description": null,
            "datetime": 1573836813,
            "cover": "Yl89b7s",
            "cover_width": 480,
            "cover_height": 854,
            "account_url": "weedywonka305",
            "account_id": 111963303,
            "privacy": "hidden",
            "layout": "blog",
            "views": 110,
            "link": "https://imgur.com/a/YkoYJnm",
            "ups": 8,
            "downs": 1,
            "points": 7,
            "score": 7,
            "is_album": true,
            "vote": null,
            "favorite": false,
            "nsfw": false,
            "section": "",
            "comment_count": 6,
            "favorite_count": 2,
            "topic": "No Topic",
            "topic_id": 29,
            "images_count": 1,
            "in_gallery": true,
            "is_ad": false,
            "tags": [
                {
                    "name": "cats",
                    "display_name": "cats",
                    "followers": 181278,
                    "total_items": 12515,
                    "following": false,
                    "is_whitelisted": false,
                    "background_hash": "xeEIpAn",
                    "thumbnail_hash": null,
                    "accent": "BF63A7",
                    "background_is_animated": false,
                    "thumbnail_is_animated": false,
                    "is_promoted": false,
                    "description": "Our feline friends",
                    "logo_hash": null,
                    "logo_destination_url": null,
                    "description_annotations": {}
                }
            ],
            "ad_type": 0,
            "ad_url": "",
            "in_most_viral": false,
            "include_album_ads": false,
            "images": [
                {
                    "id": "Yl89b7s",
                    "title": null,
                    "description": "#cats",
                    "datetime": 1573836807,
                    "type": "video/mp4",
                    "animated": true,
                    "width": 480,
                    "height": 854,
                    "size": 1388139,
                    "views": 374,
                    "bandwidth": 519163986,
                    "vote": null,
                    "favorite": false,
                    "nsfw": null,
                    "section": null,
                    "account_url": null,
                    "account_id": null,
                    "is_ad": false,
                    "in_most_viral": false,
                    "has_sound": true,
                    "tags": [],
                    "ad_type": 0,
                    "ad_url": "",
                    "edited": "0",
                    "in_gallery": false,
                    "link": "https://i.imgur.com/Yl89b7s.mp4",
                    "mp4_size": 1388139,
                    "mp4": "https://i.imgur.com/Yl89b7s.mp4",
                    "gifv": "https://i.imgur.com/Yl89b7s.gifv",
                    "hls": "https://i.imgur.com/Yl89b7s.m3u8",
                    "processing": {
                        "status": "completed"
                    },
                    "comment_count": null,
                    "favorite_count": null,
                    "ups": null,
                    "downs": null,
                    "points": null,
                    "score": null
                }
            ],
            "ad_config": {
                "safeFlags": [
                    "album",
                    "in_gallery"
                ],
                "highRiskFlags": [],
                "unsafeFlags": [
                    "sixth_mod_unsafe",
                    "under_10"
                ],
                "wallUnsafeFlags": [],
                "showsAds": false
            }
        },
        {
            "id": "dHBQBWT",
            "title": "Sprocket the old man cat",
            "description": null,
            "datetime": 1573836107,
            "cover": "EQUSXb6",
            "cover_width": 2268,
            "cover_height": 4032,
            "account_url": "kra86",
            "account_id": 59774033,
            "privacy": "hidden",
            "layout": "blog",
            "views": 126,
            "link": "https://imgur.com/a/dHBQBWT",
            "ups": 4,
            "downs": 1,
            "points": 3,
            "score": 3,
            "is_album": true,
            "vote": null,
            "favorite": false,
            "nsfw": false,
            "section": "",
            "comment_count": 0,
            "favorite_count": 0,
            "topic": "No Topic",
            "topic_id": 29,
            "images_count": 1,
            "in_gallery": true,
            "is_ad": false,
            "tags": [
                {
                    "name": "cats",
                    "display_name": "cats",
                    "followers": 181278,
                    "total_items": 12515,
                    "following": false,
                    "is_whitelisted": false,
                    "background_hash": "xeEIpAn",
                    "thumbnail_hash": null,
                    "accent": "BF63A7",
                    "background_is_animated": false,
                    "thumbnail_is_animated": false,
                    "is_promoted": false,
                    "description": "Our feline friends",
                    "logo_hash": null,
                    "logo_destination_url": null,
                    "description_annotations": {}
                },
                {
                    "name": "pets",
                    "display_name": "pets",
                    "followers": 582340,
                    "total_items": 26396,
                    "following": false,
                    "is_whitelisted": false,
                    "background_hash": "A3E5z2R",
                    "thumbnail_hash": null,
                    "accent": "24565E",
                    "background_is_animated": false,
                    "thumbnail_is_animated": false,
                    "is_promoted": false,
                    "description": "all things animal",
                    "logo_hash": null,
                    "logo_destination_url": null,
                    "description_annotations": {}
                }
            ],
            "ad_type": 0,
            "ad_url": "",
            "in_most_viral": false,
            "include_album_ads": false,
            "images": [
                {
                    "id": "EQUSXb6",
                    "title": null,
                    "description": "Sleepy old man cat said good morning and good bye to me on my way to work. He got treats and lots of scritches before because just look at that cute face! He is 18 and a half years old but such a sweetheart.",
                    "datetime": 1573835970,
                    "type": "image/jpeg",
                    "animated": false,
                    "width": 2268,
                    "height": 4032,
                    "size": 5089037,
                    "views": 231,
                    "bandwidth": 1175567547,
                    "vote": null,
                    "favorite": false,
                    "nsfw": null,
                    "section": null,
                    "account_url": null,
                    "account_id": null,
                    "is_ad": false,
                    "in_most_viral": false,
                    "has_sound": false,
                    "tags": [],
                    "ad_type": 0,
                    "ad_url": "",
                    "edited": "0",
                    "in_gallery": false,
                    "link": "https://i.imgur.com/EQUSXb6.jpg",
                    "comment_count": null,
                    "favorite_count": null,
                    "ups": null,
                    "downs": null,
                    "points": null,
                    "score": null
                }
            ],
            "ad_config": {
                "safeFlags": [
                    "album",
                    "in_gallery",
                    "onsfw_mod_safe",
                    "gallery"
                ],
                "highRiskFlags": [],
                "unsafeFlags": [
                    "sixth_mod_unsafe",
                    "under_10"
                ],
                "wallUnsafeFlags": [],
                "showsAds": false
            }
        }   
],
    "success": true,
    "status": 200
}
""".trimIndent()